---

- name: Adding Elastic PGP key 
  rpm_key:
    key: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    state: present

    #- name: Installing apt transport https
    #apt:
    #name: apt-transport-https
    #state: present

- name: Adding filebeat 7.x repository
  yum:
    name: filebeat 
    state: present 
#    update_cache: yes

- name: Installing filebeat from repository
  yum: 
    name: filebeat
    state: present
    update_cache: yes

- name: Copying config file 
  template: 
    src: filebeat.j2
    dest: /etc/filebeat/filebeat.yml

- name: Reloading systemd daemon
  systemd: 
    daemon_reload: yes

- name: Enabling filebeat.service
  systemd:
    name: filebeat.service
    enabled: yes

- name: Start filebeat.service
  systemd: 
    name: filebeat.service
    state: restarted
  become: true
